[project]
name = "ez_memprof"
version = "0.0.1"

[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"


# [tool.tox]
# legacy_tox_ini = """
# [tox]
# envlist = py3.8
# 
# [testenv]
# deps = 
# 	pytest >= 7.0.0
# 
# commands = pytest
# """